### PR TITLE
Fix: Corrected grammar and added html tags

### PR DESCRIPTION
**Pull request by Cavein254**
The HTML format was incomplete needed correction. Also, corrected some of the grammar.

### CODE REVIEW

**Comment by hridaya423** [comment]
Thanks, Will Check & Merge

**Review by hridaya423 — APPROVED** [review]
Can Be Merged

**Comment by hridaya423** [comment]
@Cavein254 Can you please take merge new changes with main branch

**Comment by hridaya423** [comment]
Merge Conflicts are there, Please merge new changes and then edit..

**Comment by hridaya423** [comment]
Could you please try to fix the merge conflicts, I am not able to change..

**Comment by Cavein254** [comment]
Sorry for the late response but I did resolve the conflicts

**Comment by hridaya423** [comment]
image
 
I am not able to merge, please check

**Pull request closed without merging**
